apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyayclient-deployment
  labels:
    app: nyayclient
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nyayclient
  template:
    metadata:
      labels:
        app: nyayclient
    spec:
      containers:
      - name: nyayclient
        image: akhilbmenon/nyayclient.ai:${BUILD_NUMBER}   # Jenkins replaces this
        imagePullPolicy: Always
        ports:
        - containerPort: 8503
        resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: nyayclient-service
  labels:
    app: nyayclient
spec:
  selector:
    app: nyayclient
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8503
    nodePort: 30011   # Change to LoadBalancer if using cloud
  type: NodePort