[theme]
primaryColor = "#2563EB"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1E293B"
font = "inter"
sidebarState = "expanded"

[server]
enableCORS = false
enableXsrfProtection = true

[client]
suppressDeprecationWarnings = true

[runner]
magicEnabled = true

# Hide default pages nav
[feature]
navigation_mode = "simple"  # or "complex"